/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.alissonlima.printjasper;

import br.com.alissonlima.printjasper.exporters.JasperViewerExporter;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;

import java.io.InputStream;
import java.util.Collections;

class AppTest {
    public static void main(String[] args) {
        try{
            ClassLoader loader = Thread.currentThread().getContextClassLoader();
            InputStream jasperIS = loader.getResourceAsStream("report.jasper");

            JasperData jasperData = new JasperData();
            jasperData.jasperInputStream = jasperIS;

            String content = "This is a <style isBold=\"true\" isItalic=\"true\" isUnderline=\"true\">static text</style> \n" +
                    "\telement containing styled text. <style backcolor=\"yellow\" isBold=\"true\" isItalic=\"true\">Styled text</style> \n" +
                    "\telements are introduced by setting the <style forecolor=\"blue\" isItalic=\"true\">markup</style> attribute \n" +
                    "\tavailable for the <style isBold=\"true\" forecolor=\"magenta\">textElement</style> tag to \n" +
                    "\t<style forecolor=\"red\" isItalic=\"true\">styled</style> and by formatting the text content using nested \n" +
                    "\t<style isBold=\"true\" forecolor=\"green\">style</style> tags and simple HTML tags.\t" +
                    "<style size=\"16\">1</style>\\n<style size=\"24\">2</style>\\n<style size=\"32\">3</style>\n";

            jasperData.jrDataSource = new JRBeanCollectionDataSource(Collections.singleton(new Data(content)));

//            new JasperHtmlExporter(jasperData).exportToFile("/Users/alissonlima/teste.html");

            JasperViewerExporter exporter = new JasperViewerExporter(jasperData);
            exporter.displayReport();

        } catch(Exception e) {
            e.printStackTrace();
        }
    }
}
